Spaceteam proxy stuff
UCLA-CS130/Team07 pull request #12
Opened 2017-03-08 19:21 UTC by jasonsliu

According to the TA, we need to submit this tonight.
Thank you!

2017-03-08 19:49 UTC, nikhilshridhar requested changes

2017-03-08 19:49 UTC, nikhilshridhar commented on spaceteam_proxy_handler.cpp
> +SpaceteamProxyHandler::result_type SpaceteamProxyHandler::consume(char input){
Did you guys get this function from an outside boost library? If so you should cite a source for it at the top.

2017-03-08 19:49 UTC, nikhilshridhar commented on spaceteam_proxy_handler.hpp
> +  virtual ~SpaceteamProxyHandler();
Can you fix the indentation here for the virtual destructor?

2017-03-08 19:49 UTC, nikhilshridhar commented on spaceteam_proxy_handler.hpp
> +
Again, if you got this function from an outside boost library, can you please cite it at the top?

2017-03-08 19:49 UTC, nikhilshridhar commented on spaceteam_proxy_handler_test.cpp
> +}
Can you make sure for all the new files that you added, you do a single tab of indentation? That is how we would like the format to be. I've seen in some of your files that you have a tab in some of them and a single space in others. Just make sure all the indentations are single tabbed.

2017-03-08 19:49 UTC, nikhilshridhar commented on Makefile
> +SRCFILES = server.cpp response.cpp request.cpp request_parser.cpp config.cc config_parser.cc request_handler.cpp echo_handler.cpp file_handler.cpp not_found_handler.cpp status_handler.cpp server_stat
Also, make sure in the Makefile that you add your unit-test file to the test target and your proxy_handler cpp file in the run_coverage target. Look at how the other team who did their proxy handler on ours did this.

2017-03-08 20:04 UTC, jasonsliu commented on spaceteam_proxy_handler.cpp
> +SpaceteamProxyHandler::result_type SpaceteamProxyHandler::consume(char input){
Good point, we put the reference in our own repository, but forgot it here.

2017-03-08 20:06 UTC, jasonsliu commented on spaceteam_proxy_handler.hpp
> +
We'll let the citation live in the .cpp file

2017-03-09 00:46 UTC, creator23 requested changes
Hi, some of the code, specifically the consume code that you wrote in the proxy_handler file is already present in our codebase, please see request_parser.cpp and modify your code to use this since we would want to avoid redundant duplication.

2017-03-09 00:46 UTC, creator23 commented on spaceteam_proxy_handler.cpp
> +		boost::asio::write(sock,
Why is the spacing here this way?

2017-03-09 00:46 UTC, creator23 commented on spaceteam_proxy_handler.cpp
> +SpaceteamProxyHandler::result_type SpaceteamProxyHandler::consume(char input){
This code is duplicated, please check request_parser.cpp

2017-03-09 02:02 UTC, jasonsliu commented on spaceteam_proxy_handler.cpp
> +SpaceteamProxyHandler::result_type SpaceteamProxyHandler::consume(char input){
It's not duplicated! Our's is different from yours, though a decent amount is the same.

2017-03-09 06:24 UTC, jasonsliu commented
Hi Team07, it's getting pretty close to our deadline. Are there any more issues we need to address?

2017-03-09 06:47 UTC, creator23 approved these changes

2017-03-09 06:48 UTC, creator23 approved these changes
Code looks good, we'll merge it in soon.

2017-03-09 08:09 UTC, jasonsliu commented
It's past the deadline, could we please merge it...

2017-03-11 09:08 UTC, merged